function BudgetSheetLoader() {
  return (
    <div className="animate-pulse overflow-x-auto">
      <div className="min-w-[1000px]">
        <div className="flex gap-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-5">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
          <div className="w-full h-8 bg-slate-200 rounded-md"></div>
        </div>
      </div>
    </div>
  );
}

export default BudgetSheetLoader;
